/**
 * 전국 공공와이파이 표준 데이터셋 (WiFiSpot Dataset)
 * 대한민국 전역 (서울, 경기/인천, 부산, 대구, 대전, 광주, 울산, 세종, 강원, 충청, 전라, 경상, 제주)
 */

const REGIONS = [
  {
    "id": "all",
    "name": "전국 전체",
    "lat": 36.3504,
    "lng": 127.3845,
    "zoom": 7
  },
  {
    "id": "seoul",
    "name": "서울",
    "lat": 37.5665,
    "lng": 126.978,
    "zoom": 13
  },
  {
    "id": "gyeonggi",
    "name": "경기/인천",
    "lat": 37.4138,
    "lng": 126.92,
    "zoom": 11
  },
  {
    "id": "busan",
    "name": "부산/울산/경남",
    "lat": 35.1796,
    "lng": 129.0756,
    "zoom": 12
  },
  {
    "id": "daegu",
    "name": "대구/경북",
    "lat": 35.8714,
    "lng": 128.6014,
    "zoom": 12
  },
  {
    "id": "daejeon",
    "name": "대전/세종/충청",
    "lat": 36.3504,
    "lng": 127.3845,
    "zoom": 12
  },
  {
    "id": "gwangju",
    "name": "광주/전라",
    "lat": 35.1595,
    "lng": 126.8526,
    "zoom": 12
  },
  {
    "id": "gangwon",
    "name": "강원",
    "lat": 37.8228,
    "lng": 128.1555,
    "zoom": 10
  },
  {
    "id": "jeju",
    "name": "제주",
    "lat": 33.4996,
    "lng": 126.5312,
    "zoom": 11
  }
];

const PUBLIC_WIFI_DATA = [
  {
    "id": "WIFI-SEL-01",
    "region": "seoul",
    "regionName": "서울",
    "name": "서울시청 본관 로비",
    "category": "public",
    "categoryName": "공공기관",
    "address": "서울특별시 중구 세종대로 110",
    "detailLocation": "본관 1층 안내데스크 및 민원실 로비",
    "lat": 37.566535,
    "lng": 126.977969,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 서울시",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps (WiFi 6)",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-SEL-02",
    "region": "seoul",
    "regionName": "서울",
    "name": "서울광장 잔디광장",
    "category": "park",
    "categoryName": "공원/광장",
    "address": "서울특별시 중구 태평로1가 54-3",
    "detailLocation": "서울도서관 앞 잔디광장 벤치 일대",
    "lat": 37.5658,
    "lng": 126.9781,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "SKT / 서울시",
    "indoorOutdoor": "실외",
    "speed": "최대 500Mbps",
    "installYear": "2022",
    "status": "good"
  },
  {
    "id": "WIFI-SEL-03",
    "region": "seoul",
    "regionName": "서울",
    "name": "서울도서관 스마트열람실",
    "category": "library",
    "categoryName": "도서관/학습",
    "address": "서울특별시 중구 세종대로 110 옛시청사",
    "detailLocation": "2층 일반자료실 및 디지털자료실",
    "lat": 37.566318,
    "lng": 126.97828,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "LGU+ / 서울시",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps (WiFi 6)",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-SEL-04",
    "region": "seoul",
    "regionName": "서울",
    "name": "광화문광장 해치마당",
    "category": "park",
    "categoryName": "공원/광장",
    "address": "서울특별시 종로구 세종대로 175",
    "detailLocation": "지하 해치마당 쉼터 및 세종대왕상 주변",
    "lat": 37.5714,
    "lng": 126.9768,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 서울시",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-SEL-05",
    "region": "seoul",
    "regionName": "서울",
    "name": "종각역 지하쇼핑센터 쉼터",
    "category": "subway",
    "categoryName": "지하철/교통",
    "address": "서울특별시 종로구 종로 73 지하",
    "detailLocation": "종각역 4번~5번 출구 연결통로 쉼터",
    "lat": 37.57018,
    "lng": 126.98305,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 서울교통공사",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-SEL-06",
    "region": "seoul",
    "regionName": "서울",
    "name": "인사동 쌈지길 중앙정원",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "서울특별시 종로구 인사동길 44",
    "detailLocation": "쌈지길 1층 중정 야외 안내소 옆",
    "lat": 37.5743,
    "lng": 126.9849,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "LGU+ / 종로구",
    "indoorOutdoor": "실외",
    "speed": "최대 500Mbps",
    "installYear": "2022",
    "status": "good"
  },
  {
    "id": "WIFI-SEL-07",
    "region": "seoul",
    "regionName": "서울",
    "name": "강남역 스마트 버스쉘터",
    "category": "subway",
    "categoryName": "지하철/교통",
    "address": "서울특별시 강남구 강남대로 396",
    "detailLocation": "강남역 11번 출구 앞 중앙버스정류장 양방향",
    "lat": 37.498085,
    "lng": 127.027582,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 서울시",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps (WiFi 6)",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-SEL-08",
    "region": "seoul",
    "regionName": "서울",
    "name": "강남역 지하상가 만남의 광장",
    "category": "subway",
    "categoryName": "지하철/교통",
    "address": "서울특별시 강남구 강남대로 지하 396",
    "detailLocation": "2호선-신분당선 환승통로 지하 1층 허브",
    "lat": 37.49795,
    "lng": 127.02762,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "SKT / 서울교통공사",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-SEL-09",
    "region": "seoul",
    "regionName": "서울",
    "name": "국립어린이청소년도서관",
    "category": "library",
    "categoryName": "도서관/학습",
    "address": "서울특별시 강남구 테헤란로7길 21",
    "detailLocation": "1층 어린이자료실 및 북카페 테라스",
    "lat": 37.50085,
    "lng": 127.0298,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 국립도서관",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-SEL-10",
    "region": "seoul",
    "regionName": "서울",
    "name": "코엑스 밀레니엄광장",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "서울특별시 강남구 영동대로 513",
    "detailLocation": "삼성역 5,6번 출구 연결광장 및 스타필드 입구",
    "lat": 37.5088,
    "lng": 127.0598,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "SKT / 강남구",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-SEL-11",
    "region": "seoul",
    "regionName": "서울",
    "name": "홍대입구역 경의선 숲길",
    "category": "park",
    "categoryName": "공원/광장",
    "address": "서울특별시 마포구 연남동 260-31",
    "detailLocation": "3번 출구 방면 잔디마당 및 벤치 일대",
    "lat": 37.5583,
    "lng": 126.9254,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 마포구",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps (WiFi 6)",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-SEL-12",
    "region": "seoul",
    "regionName": "서울",
    "name": "여의도 한강공원 물빛광장",
    "category": "park",
    "categoryName": "공원/광장",
    "address": "서울특별시 영등포구 여의동로 330",
    "detailLocation": "여의나루역 2번 출구 한강변 피크닉 쉼터",
    "lat": 37.5284,
    "lng": 126.9332,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 한강사업본부",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-SEL-13",
    "region": "seoul",
    "regionName": "서울",
    "name": "서울역 스마트 환승센터",
    "category": "subway",
    "categoryName": "지하철/교통",
    "address": "서울특별시 중구 한강대로 405",
    "detailLocation": "서울역 1번 출구 앞 버스환승센터 3번 승강장",
    "lat": 37.5552,
    "lng": 126.9708,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "SKT / 한국철도공사",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-SEL-14",
    "region": "seoul",
    "regionName": "서울",
    "name": "용산역 아이파크몰 야외광장",
    "category": "subway",
    "categoryName": "지하철/교통",
    "address": "서울특별시 용산구 한강대로23길 55",
    "detailLocation": "용산역 1번 출구 광장 및 대합실",
    "lat": 37.5298,
    "lng": 126.9647,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 용산구",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-SEL-15",
    "region": "seoul",
    "regionName": "서울",
    "name": "잠실 롯데월드타워 아레나광장",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "서울특별시 송파구 올림픽로 300",
    "detailLocation": "월드타워 잔디광장 괴테동상 앞 쉼터",
    "lat": 37.5132,
    "lng": 127.103,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 송파구",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-SEL-16",
    "region": "seoul",
    "regionName": "서울",
    "name": "동대문 디자인플라자(DDP) 어울림광장",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "서울특별시 중구 을지로 281",
    "detailLocation": "DDP 지하 2층 어울림광장 안내데스크 앞",
    "lat": 37.5668,
    "lng": 127.0095,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "SKT / 서울시",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-PUS-01",
    "region": "busan",
    "regionName": "부산",
    "name": "부산역 광장 유라시아 플랫폼",
    "category": "subway",
    "categoryName": "지하철/교통",
    "address": "부산광역시 동구 중앙대로 206",
    "detailLocation": "부산역 1번 출구 유라시아플랫폼 야외데크",
    "lat": 35.1152,
    "lng": 129.0422,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 부산시",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps (WiFi 6)",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-PUS-02",
    "region": "busan",
    "regionName": "부산",
    "name": "해운대 해수욕장 스마트비치 광장",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "부산광역시 해운대구 해운대해변로 264",
    "detailLocation": "이벤트광장 관광안내소 및 해변 산책로",
    "lat": 35.1587,
    "lng": 129.1604,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "SKT / 해운대구",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-PUS-03",
    "region": "busan",
    "regionName": "부산",
    "name": "광안리 해변 테마거리",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "부산광역시 수영구 광안해변로 219",
    "detailLocation": "광안리 만남의광장 및 차없는문화거리 쉼터",
    "lat": 35.1532,
    "lng": 129.1187,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 수영구",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-PUS-04",
    "region": "busan",
    "regionName": "부산",
    "name": "서면 지하도상가 만남의 광장",
    "category": "subway",
    "categoryName": "지하철/교통",
    "address": "부산광역시 부산진구 중앙대로 지하 737",
    "detailLocation": "서면역 1호선-2호선 환승홀 중앙분수대",
    "lat": 35.1578,
    "lng": 129.0594,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "LGU+ / 부산교통공사",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-PUS-05",
    "region": "busan",
    "regionName": "부산",
    "name": "부산광역시청 시민홀",
    "category": "public",
    "categoryName": "공공기관",
    "address": "부산광역시 연제구 중앙대로 1001",
    "detailLocation": "시청 1층 로비 및 행복민원실",
    "lat": 35.1798,
    "lng": 129.075,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 부산시",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-PUS-06",
    "region": "busan",
    "regionName": "부산",
    "name": "벡스코(BEXCO) 제1전시장 로비",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "부산광역시 해운대구 APEC로 55",
    "detailLocation": "제1전시장 1층 글래스홀 및 야외광장",
    "lat": 35.1691,
    "lng": 129.1362,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "SKT / 부산시",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps (WiFi 6)",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-PUS-07",
    "region": "busan",
    "regionName": "부산",
    "name": "자갈치시장 친수공간",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "부산광역시 중구 자갈치해안로 52",
    "detailLocation": "자갈치시장 현대화건물 뒤편 수변데크",
    "lat": 35.0967,
    "lng": 129.0305,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "LGU+ / 중구",
    "indoorOutdoor": "실외",
    "speed": "최대 500Mbps",
    "installYear": "2022",
    "status": "good"
  },
  {
    "id": "WIFI-PUS-08",
    "region": "busan",
    "regionName": "부산",
    "name": "김해국제공항 국내선 터미널",
    "category": "subway",
    "categoryName": "지하철/교통",
    "address": "부산광역시 강서구 공항진입로 108",
    "detailLocation": "국내선 2층 출발대합실 3번 게이트 앞",
    "lat": 35.173,
    "lng": 128.9463,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 한국공항공사",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-PUS-09",
    "region": "busan",
    "regionName": "부산",
    "name": "부산시민공원 하야리아 잔디광장",
    "category": "park",
    "categoryName": "공원/광장",
    "address": "부산광역시 부산진구 시민공원로 73",
    "detailLocation": "방문자센터 및 도심백사장 쉼터",
    "lat": 35.1683,
    "lng": 129.0569,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "SKT / 부산시",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-TAE-01",
    "region": "daegu",
    "regionName": "대구",
    "name": "동대구역 복합환승센터 광장",
    "category": "subway",
    "categoryName": "지하철/교통",
    "address": "대구광역시 동구 동대구로 550",
    "detailLocation": "KTX 대합실 3층 및 신세계백화점 연결광장",
    "lat": 35.8797,
    "lng": 128.6285,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 대구시",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps (WiFi 6)",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-TAE-02",
    "region": "daegu",
    "regionName": "대구",
    "name": "동성로 28아트스퀘어 야외무대",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "대구광역시 중구 동성로2가 80-1",
    "detailLocation": "구 대구백화점 앞 보행전용 야외무대 쉼터",
    "lat": 35.8698,
    "lng": 128.5962,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "SKT / 중구",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-TAE-03",
    "region": "daegu",
    "regionName": "대구",
    "name": "대구광역시청 동인청사 로비",
    "category": "public",
    "categoryName": "공공기관",
    "address": "대구광역시 중구 공평로 88",
    "detailLocation": "본관 1층 민원실 대기공간",
    "lat": 35.8714,
    "lng": 128.6014,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "LGU+ / 대구시",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-TAE-04",
    "region": "daegu",
    "regionName": "대구",
    "name": "수성못 유원지 상화동산",
    "category": "park",
    "categoryName": "공원/광장",
    "address": "대구광역시 수성구 두산동 512",
    "detailLocation": "수성못 수변산책로 영상음악분수 관람데크",
    "lat": 35.8279,
    "lng": 128.6163,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 수성구",
    "indoorOutdoor": "실외",
    "speed": "최대 500Mbps",
    "installYear": "2022",
    "status": "good"
  },
  {
    "id": "WIFI-TAE-05",
    "region": "daegu",
    "regionName": "대구",
    "name": "서문시장 야시장 고객쉼터",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "대구광역시 중구 큰장로26길 45",
    "detailLocation": "서문시장 2지구 만남의 광장 및 고객지원센터",
    "lat": 35.8691,
    "lng": 128.5815,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "SKT / 중구",
    "indoorOutdoor": "실내",
    "speed": "최대 500Mbps",
    "installYear": "2022",
    "status": "good"
  },
  {
    "id": "WIFI-TAE-06",
    "region": "daegu",
    "regionName": "대구",
    "name": "대구 두류공원 2.28기념탑 광장",
    "category": "park",
    "categoryName": "공원/광장",
    "address": "대구광역시 달서구 두류공원로 200",
    "detailLocation": "코오롱 야외음악당 잔디마당",
    "lat": 35.8524,
    "lng": 128.5568,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 달서구",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-INC-01",
    "region": "gyeonggi",
    "regionName": "인천",
    "name": "인천국제공항 제1여객터미널 밀레니엄홀",
    "category": "subway",
    "categoryName": "지하철/교통",
    "address": "인천광역시 중구 공항로 272",
    "detailLocation": "1터미널 1층 입국장 중앙 문화마당",
    "lat": 37.4602,
    "lng": 126.4407,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 인천공항공사",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps (WiFi 6)",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-INC-02",
    "region": "gyeonggi",
    "regionName": "인천",
    "name": "송도 센트럴파크 이스트보트하우스",
    "category": "park",
    "categoryName": "공원/광장",
    "address": "인천광역시 연수구 컨벤시아대로 160",
    "detailLocation": "보트하우스 매표소 및 한옥마을 진입광장",
    "lat": 37.3925,
    "lng": 126.6391,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "SKT / 연수구",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-INC-03",
    "region": "gyeonggi",
    "regionName": "인천",
    "name": "부평역 지하상가 중앙광장",
    "category": "subway",
    "categoryName": "지하철/교통",
    "address": "인천광역시 부평구 광장로 16",
    "detailLocation": "부평 모두몰 만남의 광장 휴게존",
    "lat": 37.4895,
    "lng": 126.7242,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "LGU+ / 부평구",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-INC-04",
    "region": "gyeonggi",
    "regionName": "인천",
    "name": "인천 차이나타운 패루 광장",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "인천광역시 중구 차이나타운로 59번길 12",
    "detailLocation": "인천역 맞은편 제1패루(중화가) 안내소",
    "lat": 37.4754,
    "lng": 126.618,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 중구",
    "indoorOutdoor": "실외",
    "speed": "최대 500Mbps",
    "installYear": "2022",
    "status": "good"
  },
  {
    "id": "WIFI-INC-05",
    "region": "gyeonggi",
    "regionName": "인천",
    "name": "인천광역시청 나눔청사 라운지",
    "category": "public",
    "categoryName": "공공기관",
    "address": "인천광역시 남동구 정각로 29",
    "detailLocation": "본관 1층 스마트열린소통실",
    "lat": 37.4561,
    "lng": 126.7052,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "SKT / 인천시",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-GWJ-01",
    "region": "gwangju",
    "regionName": "광주",
    "name": "광주송정역 KTX 역사 환승광장",
    "category": "subway",
    "categoryName": "지하철/교통",
    "address": "광주광역시 광산구 상무대로 201",
    "detailLocation": "역사 2층 맞이방 및 1층 택시승강장 쉼터",
    "lat": 35.1378,
    "lng": 126.7915,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 광주시",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps (WiFi 6)",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-GWJ-02",
    "region": "gwangju",
    "regionName": "광주",
    "name": "국립아시아문화전당(ACC) 열린마당",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "광주광역시 동구 문화전당로 38",
    "detailLocation": "문화창조원 앞 나눔광장 및 5.18민주광장",
    "lat": 35.1466,
    "lng": 126.9205,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "SKT / 문화체육관광부",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-GWJ-03",
    "region": "gwangju",
    "regionName": "광주",
    "name": "유스퀘어 광주종합버스터미널",
    "category": "subway",
    "categoryName": "지하철/교통",
    "address": "광주광역시 서구 무진대로 904",
    "detailLocation": "1층 고속버스 대합실 및 영풍문고 앞 광장",
    "lat": 35.1601,
    "lng": 126.8812,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "LGU+ / 광주시",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-GWJ-04",
    "region": "gwangju",
    "regionName": "광주",
    "name": "광주광역시청 시민숲 잔디광장",
    "category": "public",
    "categoryName": "공공기관",
    "address": "광주광역시 서구 내방로 111",
    "detailLocation": "1층 시민홀 및 야외 음악분수대 앞",
    "lat": 35.1604,
    "lng": 126.8515,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 광주시",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-GWJ-05",
    "region": "gwangju",
    "regionName": "광주",
    "name": "상무지구 5.18기념공원 대동광장",
    "category": "park",
    "categoryName": "공원/광장",
    "address": "광주광역시 서구 상무민주로 61",
    "detailLocation": "5.18기념문화센터 입구 및 기념탑 잔디쉼터",
    "lat": 35.1534,
    "lng": 126.858,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "SKT / 서구",
    "indoorOutdoor": "실외",
    "speed": "최대 500Mbps",
    "installYear": "2022",
    "status": "good"
  },
  {
    "id": "WIFI-DJN-01",
    "region": "daejeon",
    "regionName": "대전",
    "name": "대전역 동광장 환승센터",
    "category": "subway",
    "categoryName": "지하철/교통",
    "address": "대전광역시 동구 중앙로 215",
    "detailLocation": "3층 맞이방 호국철도광장 및 서광장 꽃시계 앞",
    "lat": 36.3315,
    "lng": 127.4332,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 대전시",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps (WiFi 6)",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-DJN-02",
    "region": "daejeon",
    "regionName": "대전",
    "name": "엑스포과학공원 한빛탑 물빛광장",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "대전광역시 유성구 대덕대로 480",
    "detailLocation": "한빛탑 앞 음악분수 광장 및 야외 카페존",
    "lat": 36.3768,
    "lng": 127.3848,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "SKT / 유성구",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-DJN-03",
    "region": "daejeon",
    "regionName": "대전",
    "name": "대전광역시청 남문 시민광장",
    "category": "public",
    "categoryName": "공공기관",
    "address": "대전광역시 서구 둔산로 100",
    "detailLocation": "1층 통합민원실 및 보라매공원 연결데크",
    "lat": 36.3504,
    "lng": 127.3845,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "LGU+ / 대전시",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-DJN-04",
    "region": "daejeon",
    "regionName": "대전",
    "name": "유성온천 야외 족욕체험장",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "대전광역시 유성구 온천로 81",
    "detailLocation": "온천공원 내 한방족욕장 쉼터 정자",
    "lat": 36.3564,
    "lng": 127.3458,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 유성구",
    "indoorOutdoor": "실외",
    "speed": "최대 500Mbps",
    "installYear": "2022",
    "status": "good"
  },
  {
    "id": "WIFI-DJN-05",
    "region": "daejeon",
    "regionName": "대전",
    "name": "KAIST 학술문화관 야외정원",
    "category": "library",
    "categoryName": "도서관/학습",
    "address": "대전광역시 유성구 대학로 291",
    "detailLocation": "중앙도서관 1층 로비 및 오리연못 벤치",
    "lat": 36.3702,
    "lng": 127.3625,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / KAIST",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps (WiFi 6)",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-ULS-01",
    "region": "busan",
    "regionName": "울산",
    "name": "KTX 울산역 환승맞이방",
    "category": "subway",
    "categoryName": "지하철/교통",
    "address": "울산광역시 울주군 삼남읍 울산역로 177",
    "detailLocation": "역사 1층 매표창구 및 버스승강장 스마트쉘터",
    "lat": 35.5516,
    "lng": 129.1387,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 울산시",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-ULS-02",
    "region": "busan",
    "regionName": "울산",
    "name": "태화강 국가정원 만남의 광장",
    "category": "park",
    "categoryName": "공원/광장",
    "address": "울산광역시 중구 태화강국가정원길 154",
    "detailLocation": "십리대숲 입구 및 종합안내센터 쉼터",
    "lat": 35.5512,
    "lng": 129.3012,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "SKT / 울산시",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-ULS-03",
    "region": "busan",
    "regionName": "울산",
    "name": "울산광역시청 햇빛광장",
    "category": "public",
    "categoryName": "공공기관",
    "address": "울산광역시 남구 중앙로 201",
    "detailLocation": "본관 1층 시민민원봉사실",
    "lat": 35.5384,
    "lng": 129.3114,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "LGU+ / 울산시",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-ULS-04",
    "region": "busan",
    "regionName": "울산",
    "name": "대왕암공원 출렁다리 진입광장",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "울산광역시 동구 등대로 155",
    "detailLocation": "출렁다리 매표광장 및 해맞이전망대 쉼터",
    "lat": 35.4932,
    "lng": 129.431,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 동구",
    "indoorOutdoor": "실외",
    "speed": "최대 500Mbps",
    "installYear": "2022",
    "status": "good"
  },
  {
    "id": "WIFI-SEJ-01",
    "region": "daejeon",
    "regionName": "세종",
    "name": "정부세종청사 중앙동 로비",
    "category": "public",
    "categoryName": "공공기관",
    "address": "세종특별자치시 다솜2로 94",
    "detailLocation": "중앙동 1층 민원접견실 및 열린소통마당",
    "lat": 36.5042,
    "lng": 127.2655,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 행정안전부",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps (WiFi 6)",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-SEJ-02",
    "region": "daejeon",
    "regionName": "세종",
    "name": "세종호수공원 중앙광장",
    "category": "park",
    "categoryName": "공원/광장",
    "address": "세종특별자치시 연기면 다솜로 216",
    "detailLocation": "수상무대섬 및 은빛해변 파라솔 쉼터",
    "lat": 36.4981,
    "lng": 127.271,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "SKT / 세종시",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-SEJ-03",
    "region": "daejeon",
    "regionName": "세종",
    "name": "국립세종도서관 열린자료실",
    "category": "library",
    "categoryName": "도서관/학습",
    "address": "세종특별자치시 다솜3로 48",
    "detailLocation": "1층 로비 및 2층 정책자료실 북카페",
    "lat": 36.4998,
    "lng": 127.2692,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "LGU+ / 문화체육관광부",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-GG-01",
    "region": "gyeonggi",
    "regionName": "경기",
    "name": "수원역 복합환승센터 2층",
    "category": "subway",
    "categoryName": "지하철/교통",
    "address": "경기도 수원시 팔달구 덕영대로 924",
    "detailLocation": "수원역사 2층 맞이방 및 롯데몰 연결통로",
    "lat": 37.2659,
    "lng": 127.0003,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 수원시",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps (WiFi 6)",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-GG-02",
    "region": "gyeonggi",
    "regionName": "경기",
    "name": "판교역 크래프톤타워 야외광장",
    "category": "subway",
    "categoryName": "지하철/교통",
    "address": "경기도 성남시 분당구 분당내곡로 117",
    "detailLocation": "신분당선 판교역 1번 출구 앞 테크노밸리 광장",
    "lat": 37.3948,
    "lng": 127.1119,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "SKT / 성남시",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps (WiFi 6)",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-GG-03",
    "region": "gyeonggi",
    "regionName": "경기",
    "name": "일산 호수공원 노래하는 분수대",
    "category": "park",
    "categoryName": "공원/광장",
    "address": "경기도 고양시 일산동구 호수로 595",
    "detailLocation": "노래하는 분수대 관람스탠드 및 쉼터 매점 앞",
    "lat": 37.6628,
    "lng": 126.7571,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 고양시",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-GG-04",
    "region": "gyeonggi",
    "regionName": "경기",
    "name": "성남시청 너른못 분수광장",
    "category": "public",
    "categoryName": "공공기관",
    "address": "경기도 성남시 중원구 성남대로 997",
    "detailLocation": "1층 로비 공감전시관 및 야외 북카페",
    "lat": 37.4201,
    "lng": 127.1265,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "LGU+ / 성남시",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-GG-05",
    "region": "gyeonggi",
    "regionName": "경기",
    "name": "의정부역 행복로 시민광장",
    "category": "subway",
    "categoryName": "지하철/교통",
    "address": "경기도 의정부시 평화로 525",
    "detailLocation": "의정부역 4번 출구 앞 보행전용 쉼터",
    "lat": 37.7381,
    "lng": 127.0459,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "SKT / 의정부시",
    "indoorOutdoor": "실외",
    "speed": "최대 500Mbps",
    "installYear": "2022",
    "status": "good"
  },
  {
    "id": "WIFI-GG-06",
    "region": "gyeonggi",
    "regionName": "경기",
    "name": "용인 에버랜드 매표광장 쉼터",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "경기도 용인시 처인구 포곡읍 에버랜드로 199",
    "detailLocation": "에버랜드 정문 셔틀버스 승강장 대기실",
    "lat": 37.2933,
    "lng": 127.2025,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 용인시",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-GW-01",
    "region": "gangwon",
    "regionName": "강원",
    "name": "춘천역 KTX 역사 광장",
    "category": "subway",
    "categoryName": "지하철/교통",
    "address": "강원특별자치도 춘천시 평화로 26",
    "detailLocation": "춘천역 1번 출구 맞이방 및 관광안내센터",
    "lat": 37.8847,
    "lng": 127.7171,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 춘천시",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-GW-02",
    "region": "gangwon",
    "regionName": "강원",
    "name": "강릉역 KTX 맞이방",
    "category": "subway",
    "categoryName": "지하철/교통",
    "address": "강원특별자치도 강릉시 용지로 156",
    "detailLocation": "중앙 로비 안내데스크 및 렌터카 환승창구",
    "lat": 37.7645,
    "lng": 128.8998,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "SKT / 코레일",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps (WiFi 6)",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-GW-03",
    "region": "gangwon",
    "regionName": "강원",
    "name": "강릉 안목해변 커피거리",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "강원특별자치도 강릉시 창해로 14번길 20-1",
    "detailLocation": "안목해변 솔밭 산책로 벤치 및 야외 광장",
    "lat": 37.7718,
    "lng": 128.9482,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 강릉시",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-GW-04",
    "region": "gangwon",
    "regionName": "강원",
    "name": "속초관광수산시장(중앙시장)",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "강원특별자치도 속초시 중앙로 147번길 16",
    "detailLocation": "닭전골목 입구 및 지하 회센터 만남의 광장",
    "lat": 38.2045,
    "lng": 128.5902,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "LGU+ / 속초시",
    "indoorOutdoor": "실내",
    "speed": "최대 500Mbps",
    "installYear": "2022",
    "status": "good"
  },
  {
    "id": "WIFI-CC-01",
    "region": "daejeon",
    "regionName": "충북",
    "name": "청주 성안길 철당간 광장",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "충청북도 청주시 상당구 남문로2가 48-1",
    "detailLocation": "용두사지철당간 앞 시민쉼터 벤치",
    "lat": 36.6348,
    "lng": 127.4891,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 청주시",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-CC-02",
    "region": "daejeon",
    "regionName": "충남",
    "name": "천안아산역 KTX 2층 맞이방",
    "category": "subway",
    "categoryName": "지하철/교통",
    "address": "충청남도 아산시 배방읍 희망로 100",
    "detailLocation": "2층 중앙 맞이방 고객대기소 및 3번 출구",
    "lat": 36.7942,
    "lng": 127.1042,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "SKT / 아산시",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-CC-03",
    "region": "daejeon",
    "regionName": "충남",
    "name": "보령 대천해수욕장 머드광장",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "충청남도 보령시 해수욕장10길 5",
    "detailLocation": "머드테마거리 안내소 및 해변 무대",
    "lat": 36.3058,
    "lng": 126.5162,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "LGU+ / 보령시",
    "indoorOutdoor": "실외",
    "speed": "최대 500Mbps",
    "installYear": "2022",
    "status": "good"
  },
  {
    "id": "WIFI-JL-01",
    "region": "gwangju",
    "regionName": "전북",
    "name": "전주한옥마을 경기전 광장",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "전북특별자치도 전주시 완산구 태조로 44",
    "detailLocation": "경기전 매표소 앞 정자 쉼터 및 관광안내소",
    "lat": 35.8152,
    "lng": 127.1498,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 전주시",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps (WiFi 6)",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-JL-02",
    "region": "gwangju",
    "regionName": "전남",
    "name": "여수 이순신광장 친수스탠드",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "전라남도 여수시 선소단길 11",
    "detailLocation": "거북선 전시관 앞 수변 데크 및 야외무대",
    "lat": 34.7402,
    "lng": 127.7348,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "SKT / 여수시",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-JL-03",
    "region": "gwangju",
    "regionName": "전남",
    "name": "순천만국가정원 동문 잔디마당",
    "category": "park",
    "categoryName": "공원/광장",
    "address": "전라남도 순천시 국가정원1호길 47",
    "detailLocation": "동문 매표광장 및 순천호수정원 쉼터",
    "lat": 34.9332,
    "lng": 127.5095,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 순천시",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-JL-04",
    "region": "gwangju",
    "regionName": "전남",
    "name": "목포 평화광장 바다분수 테라스",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "전라남도 목포시 평화로 82",
    "detailLocation": "춤추는 바다분수 관람데크 및 산책로",
    "lat": 34.7938,
    "lng": 126.4258,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "LGU+ / 목포시",
    "indoorOutdoor": "실외",
    "speed": "최대 500Mbps",
    "installYear": "2022",
    "status": "good"
  },
  {
    "id": "WIFI-GS-01",
    "region": "daegu",
    "regionName": "경북",
    "name": "경주 황리단길 관광안내소",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "경상북도 경주시 포석로 1080",
    "detailLocation": "황남동 주민자치센터 및 황리단길 쉼터 광장",
    "lat": 35.8385,
    "lng": 129.2102,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 경주시",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps (WiFi 6)",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-GS-02",
    "region": "daegu",
    "regionName": "경북",
    "name": "포항 영일대 해수욕장 영일대 전망대",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "경상북도 포항시 북구 두호동 685-1",
    "detailLocation": "해상누각 영일교 입구 광장",
    "lat": 36.0592,
    "lng": 129.3789,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "SKT / 포항시",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-GS-03",
    "region": "busan",
    "regionName": "경남",
    "name": "창원 상남분수광장 쉼터",
    "category": "park",
    "categoryName": "공원/광장",
    "address": "경상남도 창원시 성산구 마디미로 28",
    "detailLocation": "상남상업지구 중앙 바닥분수 쉼터",
    "lat": 35.2215,
    "lng": 128.6835,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 창원시",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-GS-04",
    "region": "busan",
    "regionName": "경남",
    "name": "통영 중앙전통시장 동피랑 입구",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "경상남도 통영시 중앙시장1길 14-16",
    "detailLocation": "문화마당 강구안 친수광장 쉼터",
    "lat": 34.8452,
    "lng": 128.4239,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "LGU+ / 통영시",
    "indoorOutdoor": "실외",
    "speed": "최대 500Mbps",
    "installYear": "2022",
    "status": "good"
  },
  {
    "id": "WIFI-JJ-01",
    "region": "jeju",
    "regionName": "제주",
    "name": "제주국제공항 1층 3번 게이트",
    "category": "subway",
    "categoryName": "지하철/교통",
    "address": "제주특별자치도 제주시 공항로 2",
    "detailLocation": "1층 국내선 도착장 종합관광안내센터 앞",
    "lat": 33.5065,
    "lng": 126.4932,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 제주도",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps (WiFi 6)",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-JJ-02",
    "region": "jeju",
    "regionName": "제주",
    "name": "제주 동문재래시장 고객지원센터",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "제주특별자치도 제주시 관덕로14길 20",
    "detailLocation": "동문야시장 8번 출구 고객쉼터 및 로비",
    "lat": 33.5126,
    "lng": 126.5284,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "SKT / 제주시",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-JJ-03",
    "region": "jeju",
    "regionName": "제주",
    "name": "서귀포 매일올레시장 야외광장",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "제주특별자치도 서귀포시 중앙로62번길 18",
    "detailLocation": "시장 중앙 수로쉼터 및 야외 문화공연장",
    "lat": 33.2498,
    "lng": 126.5638,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 서귀포시",
    "indoorOutdoor": "실외",
    "speed": "최대 500Mbps",
    "installYear": "2022",
    "status": "good"
  },
  {
    "id": "WIFI-JJ-04",
    "region": "jeju",
    "regionName": "제주",
    "name": "성산일출봉 매표광장 쉼터",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "제주특별자치도 서귀포시 성산읍 일출로 284-12",
    "detailLocation": "탐방안내소 앞 야외데크 및 잔디쉼터",
    "lat": 33.4621,
    "lng": 126.9368,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "LGU+ / 제주도",
    "indoorOutdoor": "실외",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  },
  {
    "id": "WIFI-JJ-05",
    "region": "jeju",
    "regionName": "제주",
    "name": "협재해수욕장 종합상황실",
    "category": "tourist",
    "categoryName": "관광/문화",
    "address": "제주특별자치도 제주시 한림읍 한림로 329-10",
    "detailLocation": "백사장 비양도 전망 벤치 및 야외 샤워장 앞",
    "lat": 33.3938,
    "lng": 126.2397,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "SKT / 제주시",
    "indoorOutdoor": "실외",
    "speed": "최대 500Mbps",
    "installYear": "2022",
    "status": "good"
  },
  {
    "id": "WIFI-JJ-06",
    "region": "jeju",
    "regionName": "제주",
    "name": "제주특별자치도청 제1청사 본관",
    "category": "public",
    "categoryName": "공공기관",
    "address": "제주특별자치도 제주시 문연로 6",
    "detailLocation": "1층 로비 민원상담실 및 청사 앞 공원 쉼터",
    "lat": 33.489,
    "lng": 126.4983,
    "ssid": "Public WiFi Free",
    "ssidSecure": "Public WiFi Secure",
    "provider": "KT / 제주도",
    "indoorOutdoor": "실내",
    "speed": "최대 1Gbps",
    "installYear": "2023",
    "status": "good"
  }
];

// 카테고리 메타데이터
const CATEGORIES = {
  all: { label: "전체", icon: "fa-border-all", color: "#3B82F6" },
  subway: { label: "지하철/교통", icon: "fa-train-subway", color: "#F59E0B" },
  public: { label: "공공기관", icon: "fa-building-columns", color: "#6366F1" },
  library: { label: "도서관/학습", icon: "fa-book-open", color: "#10B981" },
  park: { label: "공원/광장", icon: "fa-tree", color: "#22C55E" },
  tourist: { label: "관광/문화", icon: "fa-landmark", color: "#EC4899" },
  welfare: { label: "복지/편의", icon: "fa-hands-holding-circle", color: "#8B5CF6" }
};
